import { createApp } from "vue";
import "./index.css";
import "./App.css";
import App from "./App.vue";
import "element-plus/dist/index.css";
import ElementPlus from "element-plus";
import { Clock } from "@element-plus/icons-vue";
import { Calendar } from "@element-plus/icons-vue";
import { House } from "@element-plus/icons-vue";
import { Avatar } from "@element-plus/icons-vue";
import { Tools } from "@element-plus/icons-vue";
import { HomeFilled } from "@element-plus/icons-vue";
import { LocationFilled } from "@element-plus/icons-vue";
import { PhoneFilled } from "@element-plus/icons-vue";
import { Delete, Edit } from "@element-plus/icons-vue";
import { Key, Plus, InfoFilled } from "@element-plus/icons-vue";

const app = createApp(App);

app.use(ElementPlus);
app.component("Clock", Clock);
app.component("Calendar", Calendar);
app.component("House", House);
app.component("Avatar", Avatar);
app.component("Key", Key);
app.component("Tools", Tools);
app.component("HomeFilled", HomeFilled);
app.component("LocationFilled", LocationFilled);
app.component("PhoneFilled", PhoneFilled);
app.component("Plus", Plus);
app.component("InfoFilled", InfoFilled);
app.component("Delete", Delete);
app.component("Edit", Edit);
app.mount("#app");
